apiVersion: v1
kind: Service
metadata:
  name: digitaltwins-device-simulator-service
  namespace: developerautomation-xavgy
  labels:
    app: digitaltwins-device-simulator-service
spec:
  clusterIP: None
  selector:
    app: digitaltwins-device-simulator-service
---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: digitaltwins-device-simulator
  namespace: developerautomation-xavgy
spec: 
  replicas: 2
  serviceName: digitaltwins-device-simulator-service
  selector:
    matchLabels:
      app: digitaltwins-device-simulator
  template:
    metadata:
      labels:
        app: digitaltwins-device-simulator
    spec:
      containers:
        - name: digitaltwins-device-simulator
          image: digitaltwins-device-simulator:latest
          imagePullPolicy: IfNotPresent
          env:
            - name: AZ_IOT_DEVICE_ID
              valueFrom:
                fieldRef:
                  fieldPath: metadata.name
            - name: AZ_IOT_HUB_NAME
              value: DigitalTwinsHub