apiVersion: v1
kind: Secret
metadata:
  name: digitaltwins-management-kafka-credentials
  namespace: developerautomation-xavgy
type: Opaque
data:
  username: #(KAFKA_USERNAME)
  password: #(KAFKA_PASSWORD)